stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-jdk-8
          shellScript: mvn clean install  --settings settings.xml
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: rancher-repo:${CICD_GIT_BRANCH}
          #pushRemote: true
          #registry: images.kylinos.cn
        env:
          PLUGIN_INSECURE: "true"
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
timeout: 60
notification: {}
